# Generated by Django 4.2.6 on 2023-10-31 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Junior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_i_prezime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('broj_telefona', models.CharField(max_length=15)),
                ('kratak_opis', models.TextField()),
                ('dodatni_it_skilovi', models.TextField()),
                ('git_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('pdf_cv', models.FileField(blank=True, null=True, upload_to=website.models.generate_unique_filename)),
                ('image', models.ImageField(upload_to=website.models.generate_unique_filename)),
                ('prosjecna_ocjena', models.FloatField(default=0)),
                ('broj_ocjena', models.PositiveIntegerField(default=0)),
                ('primarni_jezik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='junior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocjena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocjena', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('ocijenjeni_junior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocjenjeni_junior', to='website.junior')),
                ('ocjenjivac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocjenjivac', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ocjenjivac', 'ocijenjeni_junior')},
            },
        ),
    ]
